### ISSUE TITLE
Pages with webparts not provisionned

### ISSUE THREAD

**Issue by AnassKartit** [OfficeDev/PnP-Partner-Pack#115]
when provisionning a site from a site collection that has wikipages with webparts, the page are created without webparts as the original one.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. So far we do not export content, just artifacts/settings/branding from the source template site. If you like to also have contents (like webpart pages, wikipages, content pages, files, list items, etc.) you have to change the engine and for example to use a custom extensibility provider for that. Otherwise you can manually update the XML template file, to include your own files using some <pnp:File /> elements. I will close this one, but if you have any further feedback, feel free too let us know.
