### ISSUE TITLE
Not responsive on mobile

### ISSUE THREAD

**Issue by ajhstn** [OfficeDev/PnP-Partner-Pack#146]
Hey after installing and configuring, my new site collection is "responsive" within a computer browser, however it is not on a mobile device.

Is anyone experiencing this?

**Comment by PaoloPia** [comment]
Please, check if the URL of the infrastructural site collection is accessible from the public internet network (and to mobile devices, as well). Often this is the reason why you don't see the responsive design from outside your corporate network (i.e. from mobile devices).

**Comment by StfBauer** [comment]
In responsive web design it always depends on the real hardware device and while it works nowadays in many browser some might fail.
The problem in order to make SharePoint responsive is that add a viewport meta tag right after the page have been loaded.
Needless to say this should be included in the master page but is currently not part of SharePoint.

[Quirks mode](http://www.quirksmode.org/blog/archives/2011/06/dynamically_cha.html) had an article on if it is possible to change the viewport after the page have been loaded. As they tested it works on most browsers except firefox. The page they loaded already contained a viewport meta tag.

Their [compatibility chart](http://www.quirksmode.org/mobile/tableViewport.html#metaviewport) they list that it might be tricky to change or add viewport meta afterwards.

It's a general problem of SharePoint, the sample and different devices since you only have limited resources to test such solutions.
A different sample of Office PNP covers the meta viewport problem more specific. The [Branding.InjectResponsiveCSS](https://github.com/OfficeDev/PnP/tree/master/Samples/Branding.InjectResponsiveCSS).
List a workaround for publishing site and how to add the meta viewport tag.
The problem still exists on Team Sites and it cannot be guaranteed that it works in all cases, browser and devices.

**Comment by PaoloPia** [comment]
Thanks @StfBauer,
right now in the PnP Partner Pack v. 2.0 we use the EnableResponsiveUI extension method of PnP Core Library, which embeds the following JS in the target site:

https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Resources/SP-Responsive-UI.js

As you can see, there we create on the fly the viewpoirt meta element. On the contrary in the old PnP Partner Pack v. 1.x we used a dedicate JS file, which was missing that element.

**Comment by StfBauer** [comment]
@PaoloPia Yeah but you still load viewport meta into the page which cause issues on some browsers. The viewport meta should be right there before the rendering of the page starts and this is hard to achieve by using JavaScript.

Am I wrong?

You event still have additonal delay through the loading of JQuery from a CDN which can cause additional problems when it takes longer to load jQuery and the page already have been rendered.
With some simpel tweaks you can transform the same script to work without jQuery.

**Comment by PaoloPia** [comment]
Thanks @StfBauer,
About the viewport meta tag, yes we load it through JS. We tested it on many mobile devices and looks like it works, of course there is no guarantee to have it working on 100% of devices.
About removing jQuery dependency, if you like - and if you have time - please submit a PR with the suggested changes and we will be more than happy to merge it. In the meantime I will close this issue, because it is in the wrong repository. Eventually please submit any PR or issue related to the Responsive UI in the PnP-Sites-Core repo, or in the PnP-Tools repo. Thanks.
