### ISSUE TITLE
Use of Azure Classic Portal

### ISSUE THREAD

**Issue by DeanGross** [OfficeDev/PnP-Partner-Pack#152]
How come the classic Azure portal is used to create the App Service instead of the Portal? Would there be any benefit to putting the PnP artifacts into an Azure Resource Group?
I'm looking forward to demonstrating this to my new client.

**Comment by PaoloPia** [comment]
Hi,
We are in the process of updating the documentation and the videos, using the new Azure Management Portal for configuring the Azure AD Application. In fact, the Azure AD management UI has been released in preview just few weeks ago, within the new portal and when we recorded videos it wasn't there, yet. If you like, you can use that one instead of the classic one.

About the second question, yes if you like you can define a Resource Group for the resources used by the PnP Partner Pack.

More in general, as we just released the PnP Partner Pack v.2, we are in the process of releasing a new setup tool, as well. It will be a Windows desktop application (WPF) and it will manage all of the setups steps for you. Under the cover, we will use the Microsoft Graph API. Thus, all the Azure resources will be created by this new tool, and the documentation and videos will follow this new approach.

**Comment by DeanGross** [comment]
thanks for the update, I am looking forward to using this with a new client.
