### ISSUE TITLE
Created Landing Page / Source Template Expectations...

### ISSUE THREAD

**Issue by 2P2-Anthony** [OfficeDev/PnP-Partner-Pack#154]
Howdy...

Maybe I don't understand how the site collection template is built or used to create the new auto-provisioned site, but I would expect that any web parts on the new site collection home page would be replicated from the site collection used to build / create the template.

For example, here is a screen shot of the source Site Collection:

![image](https://cloud.githubusercontent.com/assets/6393228/18855430/93bf1632-8407-11e6-83ed-f5203df514e4.png)

It has a couple of standard web parts showing the detail in the lists / document libraries that are part of the site collection. Nothing fancy. Now after we build a new site collection using a template created from the above image we get the following:

![image](https://cloud.githubusercontent.com/assets/6393228/18858309/fd10b290-841f-11e6-8eb5-d51461392268.png)

The logo was picked up, surprisingly, however the selected colors and the landing page customizations don't come over, which I would think would too. When a client wants to setup Auto Provisioning and creates a template for his employees to use to create the new site collections ,they want the branding (which is only the theme / color picker) and the web parts on the landing page to be setup also.

Or am I expecting too much?

**Comment by PaoloPia** [comment]
Hi,
Unfortunately the extraction of webparts from the welcome page, when acting with an AppOnly token (which is the case for the PnP Partner Pack) is not yet supported by the provisioning engine, because of a limitation in CSOM. However, CSOM has been updated a few weeks ago, and we are in the process of updating the provisioning engine accordingly. Most likely, by the next monthly release you will be able to export webparts from welcomepages, too.

**Comment by 2P2-Anthony** [comment]
Ok - looking forward to that update.
